# Generated by Django 4.0.6 on 2024-05-31 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surprise', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='day',
            field=models.CharField(choices=[('1', 'June 2nd'), ('2', 'June 6th'), ('3', 'June 10th'), ('4', 'June 14th')], max_length=1, unique=True),
        ),
    ]
