# Generated by Django 4.0.6 on 2024-05-31 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surprise', '0002_alter_message_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='id',
        ),
        migrations.AlterField(
            model_name='message',
            name='day',
            field=models.CharField(choices=[('1', 'June 2nd'), ('2', 'June 6th'), ('3', 'June 10th'), ('4', 'June 14th')], max_length=1, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.ImageField(upload_to='~/drewsurprise/surprise/images')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surprise.message')),
            ],
        ),
    ]
